//Auth
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'

//USER
export const SET_USER_PAYLOAD = 'SET_USER_PAYLOAD'
export const SET_USER_DATA = 'SET_USER_DATA'
export const RESET_USER_DATA = 'RESET_USER_DATA'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const ADD_NEW_USER = 'ADD_NEW_USER'
export const DELETE_USER = 'DELETE_USER'

//CAMP
export const SET_CAMP_PAYLOAD = 'SET_CAMP_PAYLOAD'
export const SET_CAMP_DATA = 'SET_CAMP_DATA'
export const RESET_CAMP_DATA = 'RESET_CAMP_DATA'
export const UPDATE_CAMP_DATA = 'UPDATE_CAMP_DATA'
export const ADD_NEW_CAMP = 'ADD_NEW_CAMP'
export const DELETE_CAMP = 'DELETE_CAMP'

//ORDER
export const SET_ORDER_PAYLOAD = 'SET_ORDER_PAYLOAD'
export const SET_ORDER_DATA = 'SET_ORDER_DATA'
export const RESET_ORDER_DATA = 'RESET_ORDER_DATA'
export const UPDATE_ORDER_DATA = 'UPDATE_ORDER_DATA'
export const ADD_NEW_ORDER = 'ADD_NEW_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'

//PAGINATION
export const SET_TOTAL_PAGE = 'SET_TOTAL_PAGE'
